### ISSUE TITLE
Error: File 'file' not present in dictionary

### ISSUE THREAD

**Issue by bring2dip** [mgcrea/grunt-nginclude#11]
I am trying to include the templates in an html file. There are two templates referenced in home.client.view.html. one of them is 'modules/core/views/templates/top-promoted-items.template.html'. My folder structure is:
modules
.core
..server
..client
....views
.....templates
......top-promoted-items.template.html
....home.client.view..html

the view file static path is defined in the express server. for example the file top-promoted-items.template.html is referenced as 'modules/core/views/templates/top-promoted-items.template.html'. Note that there is no '/client/' in the url. it is handeled by express. But when i tried to compile such views the grunt-nginclude gives the above error.

My nginclude config is below:
``
nginclude: {
      options: {
        discardReferencedFiles: true,
        parserOptions: {},
        replacementElementClass: 'nginclude-replaced',
        replacementElementTag: 'section'
      },
      your_target: {
        files: [{
          cwd: process.cwd(),
          src: 'modules/core/client/views/home.client.view.html',
          dest: 'public/dist'
        }]
      }
    }
``

**Comment by grandpa-codes** [comment]
The task can only do the replacements for the files it can reference. In your case you need to reference all the files on the sources. Having the option `discardReferencedFiles` set to `true` it will discard it from the output once it replaces it somewhere.
