### ISSUE TITLE
div's are being replaced instead of having content inserted since 0.4.1

### ISSUE THREAD

**Issue by firstdoit** [mgcrea/grunt-nginclude#5]
Apparently, version 0.3.0 has the correct behaviour: includes are **inserted into** the ng-include tagged element.

As of 0.4.1, this behaviour is broken and the element containing the ng-include tag is **replaced** by the included template.

**Comment by idpaterson** [comment]
This problem still exists in 0.4.1 (the latest available in npm). It does appear that the latest code in master works properly, but that requires specifying `mgcrea/grunt-nginclude#master` in package.json.

Oddly, version 0.4.1 in npm doesn't seem to match up with the repo. That version uses `$ng.replaceWith(before + include);` which does not appear in the history - possibly some local test code that was never committed?

**Comment by maiap** [comment]
A new version has been released that should solve the stated problem.

Closing this issue.
